# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  major: 1
  minor: 0
  patch: $[counter('patch', 0)]

name: $(date:MMdd)-$(BuildDefinitionName)-$(major).$(minor).$(patch)

steps:
- script: |
    dotnet restore Chronos.Net.sln
    dotnet build Chronos.Net.sln --configuration $(buildConfiguration) /p:VersionPrefix=$(major).$(minor).$(patch)
    dotnet test Chronos.Net.sln --no-build --configuration $(buildConfiguration) --logger:trx
    dotnet pack Chronos.Net.sln --no-build --configuration $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) -o $(build.artifactstagingdirectory)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/*.trx'

- task: PublishBuildArtifacts@1